### ISSUE TITLE
Integration setup fails

### ISSUE THREAD

**Issue by diegocjorge** [chris-mc1/qBittorrent-hass#1] opened 2024-02-02 21:28 UTC
I stumbled upon your integration while I was searching for a way to remotely control qBittorrent (specifically, the option to pause and resume torrents). I’m not sure if you have any interest in maintaining this repository, but if you do, could you assist me in setting it up?

Whenever I attempt to add the integration, it consistently fails (see the error log below). I am confident that my Web UI URL, login, and password are all correct because they work with the official qBittorrent integration.

Do you have any idea what might be causing this issue? My qBittorrent is running on Docker using this image: linuxserver/qbittorrent:4.6.3

`2024-02-01 20:52:05.347 WARNING (MainThread) [aioqbt.client.APIClient] Request 1/3: GET 'http://192.168.25.20:8080/api/v2/app/version'
Traceback (most recent call last):
File "/usr/local/lib/python3.11/site-packages/aioqbt/client.py", line 255, in request
raise aiohttp.ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 403, message='Forbidden', url=URL('http://192.168.25.20:8080/api/v2/app/version')
2024-02-01 20:52:05.358 WARNING (MainThread) [aioqbt.client.APIClient] Request 1/3: GET 'http://192.168.25.20:8080/api/v2/app/version'
Traceback (most recent call last):
File "/usr/local/lib/python3.11/site-packages/aioqbt/client.py", line 255, in request
raise aiohttp.ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 403, message='Forbidden', url=URL('http://192.168.25.20:8080/api/v2/app/version')
2024-02-01 20:52:05.363 WARNING (MainThread) [aioqbt.client.APIClient] Request 1/3: GET 'http://192.168.25.20:8080/api/v2/app/webapiVersion'
Traceback (most recent call last):
File "/usr/local/lib/python3.11/site-packages/aioqbt/client.py", line 255, in request
raise aiohttp.ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 403, message='Forbidden', url=URL('http://192.168.25.20:8080/api/v2/app/webapiVersion')
2024-02-01 20:52:05.367 WARNING (MainThread) [aioqbt.client.APIClient] Request 1/1: POST 'http://192.168.25.20:8080/api/v2/auth/logout'
Traceback (most recent call last):
File "/usr/local/lib/python3.11/site-packages/aioqbt/client.py", line 255, in request
raise aiohttp.ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 403, message='Forbidden', url=URL('http://192.168.25.20:8080/api/v2/app/version')
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
File "/config/custom_components/qbittorrent_alt/helpers.py", line 23, in setup_client
await client.app.version()
File "/usr/local/lib/python3.11/site-packages/aioqbt/api/app.py", line 18, in version
return await self._request_text(
^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/aioqbt/client.py", line 518, in _request_text
return await self._client().request_text(method, endpoint, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/aioqbt/client.py", line 363, in request_text
resp = await self.request(method, endpoint, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/aioqbt/client.py", line 284, in request
self._handle_error(last_exc, resp, resp_body)
File "/usr/local/lib/python3.11/site-packages/aioqbt/client.py", line 351, in _handle_error
raise exc_class.from_response(resp, message) from error
aioqbt.exc.ForbiddenError: ForbiddenError(status=403, message='Forbidden')
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/usr/local/lib/python3.11/site-packages/aioqbt/client.py", line 255, in request
raise aiohttp.ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 403, message='Forbidden', url=URL('http://192.168.25.20:8080/api/v2/auth/logout')
2024-02-01 20:52:05.375 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
File "/usr/local/lib/python3.11/site-packages/aioqbt/client.py", line 255, in request
raise aiohttp.ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 403, message='Forbidden', url=URL('http://192.168.25.20:8080/api/v2/app/version')
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
File "/usr/local/lib/python3.11/site-packages/aiohttp/web_protocol.py", line 452, in _handle_request
resp = await request_handler(request)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/aiohttp/web_app.py", line 543, in _handle
resp = await handler(request)
^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/aiohttp/web_middlewares.py", line 114, in impl
return await handler(request)
^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 85, in security_filter_middleware
return await handler(request)
^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
return await handler(request)
^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
return await handler(request)
^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 80, in ban_middleware
return await handler(request)
^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 233, in auth_middleware
return await handler(request)
^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/http/headers.py", line 31, in headers_middleware
response = await handler(request)
^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 149, in handle
result = await handler(request, **request.match_info)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/http/decorators.py", line 63, in with_admin
return await func(self, request, *args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 177, in post
return await super().post(request, flow_id)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 72, in wrapper
result = await method(view, request, data, *args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 110, in post
result = await self._flow_mgr.async_configure(flow_id, data)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 320, in async_configure
result = await self._async_handle_step(
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 416, in _async_handle_step
result: FlowResult = await getattr(flow, method)(user_input)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/qbittorrent_alt/config_flow.py", line 42, in async_step_user
await setup_client(
File "/config/custom_components/qbittorrent_alt/helpers.py", line 23, in setup_client
await client.app.version()
File "/usr/local/lib/python3.11/site-packages/aioqbt/api/app.py", line 18, in version
return await self._request_text(
^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/aioqbt/client.py", line 518, in _request_text
return await self._client().request_text(method, endpoint, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/aioqbt/client.py", line 363, in request_text
resp = await self.request(method, endpoint, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/aioqbt/client.py", line 284, in request
self._handle_error(last_exc, resp, resp_body)
File "/usr/local/lib/python3.11/site-packages/aioqbt/client.py", line 351, in _handle_error
raise exc_class.from_response(resp, message) from error
aioqbt.exc.ForbiddenError: ForbiddenError(status=403, message='Forbidden')`

**Comment by chris-mc1** [comment] 2024-02-20 19:29
Hey, 
Sorry for the long wait.
The error is caused by using an IP address instead of a domain name in the URL, which is consider unsafe by aiohttp.
Should be fixed in the newest beta release.

**Closed as completed** 2024-04-28 07:27 UTC
